version: "3"

services:
  database:
    image: mysql:8
    container_name: springsns_db
    environment:
      - MYSQL_DATABASE=snsdb
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    networks:
      - springsns_network

  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    container_name: springsns
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - springsns_network

networks:
  springsns_network: