spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://database:3306/snsdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    databse-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 20

  #  use naver smtp
  mail:
    host: smtp.naver.com
    port: 465
    username: #naver id
    password: #naver password
    properties:
      mail:
        smtp:
          ssl:
            enable: true
app:
  host: http://localhost:8080

jwt:
  secret-key: zlarbalssecret

mail:
  email: #naver email 주소