spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:~/springsns
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 20


logging:
  level:
    org:
      apache:
        coyote:
          http11: debug

app:
  host: http://localhost:8080

jwt:
  secret-key: secret